export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';
export const RECEIVE_CUSTOMERS = 'RECEIVE_CUSTOMERS';
export const FETCH_CUSTOMERS_FAILURE = 'FETCH_CUSTOMERS_FAILURE';
export const FETCH_CUSTOMER = 'FETCH_CUSTOMER';
export const RECEIVE_CUSTOMER = 'RECEIVE_CUSTOMER';
export const SAVE_CUSTOMER = 'SAVE_CUSTOMER';
export const SAVED_CUSTOMER = 'SAVED_CUSTOMER';
export const FETCH_CUSTOMER_FAILURE = 'FETCH_CUSTOMER_FAILURE';
